dist: trusty
sudo: true

language: cpp
compiler: gcc
notifications:
    slack: gqcg:13JQ7AAK5DMZPeAInhCMX6YJ
    email: false

# Travis CI's CMake version is only 3.2.2. This is a workaround (https://github.com/travis-ci/travis-ci/issues/7437) that upgrades to a newer version of CMake
before_install:
  - mkdir ${HOME}/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.9/cmake-3.9.1-Linux-x86_64.sh
  - chmod +x cmake-3.9.1-Linux-x86_64.sh
  - ./cmake-3.9.1-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license

addons:
  apt:
    packages:
    - libint2-dev

install:
  # Install Eigen3
  - hg clone https://bitbucket.org/eigen/eigen#3.2 /tmp/eigen
  - mkdir /tmp/eigen-build && cd /tmp/eigen-build
  - cmake . /tmp/eigen -DCMAKE_INSTALL_PREFIX=/opt/local
  - make
  - sudo make install

script:
  - cd /home/travis/build/lelemmen/libint-wrapper
  - mkdir build && cd build
  - cmake ..
  - make
  - make test
  - sudo make install